### PR TITLE
Clarify block/page terminology

### PR DESCRIPTION
**Pull request by mattico**
I was confused by the documentation of `DFUMemIO` because it seems to use "block" and "page" interchangeably. I wanted to clarify the terminology used and settled on the following:

A "block" is the largest buffer that can be read or programmed. A "page" is the smallest region of flash memory that can be erased.

### CODE REVIEW

**Comment by vitalyvb** [comment]
Hi @mattico , thanks for the suggestion. I agree, it's confusing. "Transfer-block" size is supposed to be the same size as the page, but it's not the case right now, especially for larger pages, and it makes things more complicated than it should be.

DFUMemIO methods are called from DFU code, which works with "blocks", but DFUMemIO's implementation works with flash and operates with pages internally.

One thing in the change I'm not sure about is that there's both "pages" and "blocks" now, supposedly in the future limited control block transfers will be fixed, and API may become confusing again?

Can "blocks" and "pages" be both removed, will it make it better? For example
```rust
const PROGRAM_TIME_MS: u32;
const ERASE_TIME_MS: u32;
const FULL_ERASE_TIME_MS: u32;

fn read(&mut self, address: u32, length: usize) -> Result<&[u8], DFUMemError>;
fn program(&mut self, address: u32, length: usize) -> Result<(), DFUMemError>;
fn erase(&mut self, address: u32) -> Result<(), DFUMemError>;
fn erase_all(&mut self) -> Result<(), DFUMemError>;
```
And perhaps page/block distinction could be in the documentation and implementation only.

Thanks

**Comment by mattico** [comment]
> Can "blocks" and "pages" be both removed, will it make it better?
> And perhaps page/block distinction could be in the documentation and implementation only.

That makes sense. Then it won't be a breaking change to change the terminology in the future.

**Comment by vitalyvb** [comment]
Thanks, @mattico, do you mind updating the minimal implementation example in src/lib.rs and README.md, CHANGELOG.md, and the tests too?

**Comment by mattico** [comment]
Done!

**Comment by vitalyvb** [comment]
Merged, thank you!
As it's a breaking change, it'll be in 0.2.0, I'll try to make a release this or next week.

**Pull request merged**
